ChatApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using ChatApp.Helpers;
using ChatApp.Models;

namespace ChatApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            if (SessionHelper.GetObjectFromJson<User>(HttpContext.Session,"user") != null) return Redirect("/chat");

            return View();
        }
    }
}

ChatApp/Controllers/RegController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChatApp.Models;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace ChatApp.Controllers
{
    public class RegController : Controller
    {
        IServiceProvider _service;
        public RegController(IServiceProvider service)
        {
            _service = service;

        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(User model)
        {
            using (var db = new ChatDbContext (_service.GetRequiredService<DbContextOptions<ChatDbContext>>()))
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        model.CreateTime = DateTime.Today;
                        await db.User.AddAsync(model);
                        await db.SaveChangesAsync();
                        return Redirect("/chat");
                    }
                    catch
                    {
                        Debug.WriteLine("Cannot save model to DB.");
                        return View();
                    }


                }
                else return View();
                


            }

                

            
        }
    }
}

ChatApp/Views/Home/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>This is a text page</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">pChat</a>
            </div>
        </div>
    </nav>
    <!-- / Navigation Bar -->

    <div class="container">
        <div class="row">
            <div class="col-md-5 col-md-offset-4">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="text-center">
                            <img class="img-thumbnail" width="150" height="150" src="@Url.Content("~/Content/no-avatar.png")" />
                        </div>
                        <form action="/login" method="post" style="margin:0" autocomplete="off">
                            <div class="form-group">
                                <input type="text" name="username" id="username" placeholder="Enter Username" class="form-control" required minlength="3" maxlength="15" />
                            </div>
                            <div class="form-group">
                                <input type="text" name="password" id="password" placeholder="Enter Password" class="form-control" required minlength="8" />
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Enter Chat</button>
                            <a asp-controller="Reg" asp-action="Create">Don't have an account? Get one!</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>